# Swap the prompt character
[character]
success_symbol = "[â®• ](bold yellow) "
error_symbol = "[âœ— ](bold red) "

# User
[username]
style_user = "yellow bold"
style_root = "red bold"
format = "ğŸ‘¹ [$user]($style) "
disabled = false
show_always = true

# Directory
[directory]
truncation_length = 3
style = "bold cyan"
read_only = "ğŸ”’"
read_only_style = "red"
format = "in ğŸ“‚ [$path]($style)[$read_only]($read_only_style) "

# Git
[git_branch]
symbol = "ğŸŒ± "
truncation_length = 10
truncation_symbol = ""

[git_commit]
commit_hash_length = 4
tag_symbol = "ğŸ”– "

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[ğŸ’ PICKING](bold red)"

[git_status]
conflicted = "ğŸ´â€â˜ "
ahead = "ğŸğŸ’¨"
behind = "ğŸ˜°"
diverged = "ğŸ˜µ"
untracked = "ğŸ¤·â€"
stashed = "ğŸ“¦"
modified = "ğŸ“"
staged = '[++\($count\)](green)'
renamed = "ğŸ‘…"
deleted = "ğŸ—‘ï¸"

# Host OS
[hostname]
ssh_only = false
style = "bold yellow"
format =  "on ğŸ’» [$hostname]($style) "
trim_at = ".companyname.com"
disabled = false

# Python
[python]
symbol = "with ğŸ "
style="bold cyan"
pyenv_version_name = true

# Time
[time]
disabled = false
use_12hr = true
style = "cyan"
format = '[$time]($style) '
time_format = "%a %D %I:%M %P"
utc_time_offset = "local"